2018-10-10 11:39 INFO     task          download-series-rss Rerunning the task in case better resolution can be achieved.
2018-10-10 11:39 INFO     download      download-series-rss Downloading: The Gifted S02E03 1080p HDTV x264-CRAVERS[rarbg]
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: [Errno 111] Connection refused
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: [Errno 111] Connection refused
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: [Errno 111] Connection refused
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: [Errno 111] Connection refused
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: [Errno -2] Name or service not known
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: [Errno -2] Name or service not known
2018-10-10 11:39 WARNING  urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff298319710>: Failed to establish a new connection: [Errno 111] Connection refused',)': /scrape?info_hash=%2A%2B%E6%94%97o%F8x%8E%9B%CA%7Dh%B5m%E0%A3%FD%24V
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:39 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:40 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:40 WARNING  torrent_alive                 Socket Error: timed out
2018-10-10 11:40 WARNING  urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff274653c90>, 'Connection to share.camoe.cn timed out. (connect timeout=30)')': /scrape?info_hash=%2A%2B%E6%94%97o%F8x%8E%9B%CA%7Dh%B5m%E0%A3%FD%24V
2018-10-10 11:40 WARNING  urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff29837c6d0>, 'Connection to tracker.tfile.co timed out. (connect timeout=30)')': /scrape?info_hash=%2A%2B%E6%94%97o%F8x%8E%9B%CA%7Dh%B5m%E0%A3%FD%24V
2018-10-10 11:40 WARNING  urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff298319f90>, 'Connection to retracker.spb.ru timed out. (connect timeout=30)')': /scrape?info_hash=%2A%2B%E6%94%97o%F8x%8E%9B%CA%7Dh%B5m%E0%A3%FD%24V
2018-10-10 11:40 WARNING  urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff298319690>, 'Connection to tracker3.itzmx.com timed out. (connect timeout=30)')': /scrape?info_hash=%2A%2B%E6%94%97o%F8x%8E%9B%CA%7Dh%B5m%E0%A3%FD%24V
2018-10-10 11:40 INFO     transmission  download-series-rss "The Gifted S02E03 1080p HDTV x264-CRAVERS[rarbg]" torrent added to transmission
2018-10-10 11:41 INFO     exec          move-series     Stdout: find: ‘/mnt/BISMARK/downloads/series/*’: No such file or directory
2018-10-10 11:41 INFO     exec          move-movies     Stdout: find: ‘/mnt/BISMARK/downloads/filmes/*’: No such file or directory
2018-10-10 11:41 INFO     subtitle_list download-subtitles File /mnt/YAMATO/Series/Channel Zero/Channel Zero - S04E01 - Ashes On My Pillow - [720p webdl h264].mkv has been in the list for 7 days. Removing from list.
2018-10-10 11:41 INFO     subtitle_list download-subtitles File /mnt/YAMATO/Series/This Is Us/This Is Us - S03E02 - A Philadelphia Story - [720p hdtv h264].mkv has been in the list for 7 days. Removing from list.
2018-10-10 11:41 INFO     subtitles     download-subtitles Name computed for /mnt/YAMATO/Series/The Good Doctor/The Good Doctor - S02E03 - 36 Hours - [hdtv h264].mkv was The Good Doctor
2018-10-10 11:41 INFO     subtitles     download-subtitles Name computed for /mnt/YAMATO/Series/9-1-1/9-1-1 - S02E04 - Stuck - [720p hdtv h264].mkv was 9-1-1
2018-10-10 11:41 INFO     subtitles     download-subtitles Name computed for /mnt/YAMATO/Series/Kidding/Kidding - S01E05 - The New You - [720p webdl h264].mkv was Kidding
2018-10-10 11:41 INFO     subtitles     download-subtitles Name computed for /mnt/YAMATO/Series/Speechless/Speechless - S03E01 - L-O-N-- LONDON (1) - [720p hdtv h264].mkv was Speechless
2018-10-10 11:41 INFO     subtitles     download-subtitles Name computed for /mnt/YAMATO/Series/The Last Ship/The Last Ship - S05E05 - Warriors - [720p webrip h265].mkv was The Last Ship
2018-10-10 11:41 INFO     api_tvdb      get-series-nextep Data for <TVDBEpisode series=Young Sheldon,season=1,episode=10> has expired, refreshing from tvdb
2018-10-10 11:41 INFO     api_tvdb      get-series-nextep Data for <TVDBEpisode series=The Flash (2014),season=5,episode=1> has expired, refreshing from tvdb
2018-10-10 11:41 ERROR    lazy_lookup   get-series-nextep Unhandled error in lazy lookup plugin: %d format: a number is required, not NoneType
2018-10-10 11:41 CRITICAL manager       get-series-nextep An unexpected crash has occurred. Writing crash report to /home/braga/flexget/crash_report.2018.10.10.114147079752.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.15.1
2018-10-10 11:42 INFO     api_tvdb      get-series-nextep Data for <TVDBEpisode series=Counterpart,season=2,episode=1> has expired, refreshing from tvdb
2018-10-10 11:42 INFO     api_tvdb      get-series-nextep Data for <TVDBEpisode series=The Good Doctor,season=2,episode=3> has expired, refreshing from tvdb
2018-10-10 11:42 INFO     api_tvdb      get-series-nextep Data for <TVDBEpisode series=Channel Zero,season=1,episode=5> has expired, refreshing from tvdb
2018-10-10 11:42 INFO     api_tvdb      get-series-nextep Data for <TVDBEpisode series=The Terror,season=2,episode=1> has expired, refreshing from tvdb
2018-10-10 11:42 ERROR    lazy_lookup   get-series-nextep Unhandled error in lazy lookup plugin: %d format: a number is required, not NoneType
Traceback (most recent call last):
  File "/home/braga/flexget/lib/python2.7/site-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/home/braga/flexget/lib/python2.7/site-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 159, in lazy_episode_lookup
    entry.update_using_map(self.episode_map, episode)
  File "/home/braga/flexget/lib/python2.7/site-packages/flexget/entry.py", line 276, in update_using_map
    v = value(source_item)
  File "/home/braga/flexget/lib/python2.7/site-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 99, in <lambda>
    'tvdb_ep_id': lambda ep: 'S%02dE%02d' % (ep.season_number, ep.episode_number)
TypeError: %d format: a number is required, not NoneType
